name: Lint and Format

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
       
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 isort
      
      - name: Run black formatting
        run: |
          black --check .
      
      - name: Run isort
        run: |
          isort --check .
      
      - name: Run flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
